version: '3.8'

services:
  # PHP and Laravel application container
  app:
    build: .
    container_name: laravel_app_2
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./public:/var/www/public
    ports:
      - "8000:9000"
    depends_on:
      - db
    networks:
      - laravel_network

  # MySQL Database
  db:
    image: mysql:latest
    container_name: mysql_db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - laravel_network

  # Composer for managing PHP dependencies
  composer:
    image: composer:latest
    container_name: composer2
    volumes:
      - .:/app
    networks:
      - laravel_network

  # Node.js for front-end build
  node:
    image: node:current-alpine3.22
    container_name: node2
    volumes:
      - .:/app
    networks:
      - laravel_network
    command: sh -c "npm install && npm run dev"

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
